services:
  # Backend Service
  - name: realtorcornerbackend
    type: web
    env: python
    region: oregon
    buildCommand: sh build.sh
    startCommand: gunicorn realtorcorner.wsgi:application
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    disk:
      name: media
      mountPath: /media
      sizeGB: 1 # Adjust this based on media storage needs
    healthCheckPath: /
    plan: free
    branch: main
    repo: https://github.com/JC-April/realtorcorner
